POST localhost:8080/lowest/price
Content-Type: application/json; charset=UTF-8

[
  {
    "prdNo": 2249846158,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 2025531185,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 34709787,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 1595538080,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 1595512385,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 1765845547,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  },
  {
    "prdNo": 3401436468,
    "partnerCd": "NAVER",
    "modelNo": "1000011357",
    "modelSubNo": "0",
    "minPrice": 21720,
    "min2ndPrice": 21755,
    "minPriceYn": "Y",
    "modelNm": "YB-2100",
    "createDt": null,
    "updateDt": null,
    "addKey": null,
    "mobileMinPrice": 0,
    "mobileMin2ndPrice": 0,
    "mobileMinPriceYn": null,
    "modelMngTypCd": "01",
    "deliveryCost": 0,
    "fullModelNo": "1000011357"
  }
]
